name: food_tracker
description: "Food Tracker"
publish_to: 'none'

version: 1.0.2+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: '>=2.3.3+1 <2.4.0'
  sqflite_common_ffi: ^2.3.4
  sqlite3_flutter_libs: ^0.5.28
  path_provider: ^2.1.5
  path: ^1.9.1
  google_generative_ai: ^0.4.6
  flutter_secure_storage: ^9.2.4
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  image: ^4.5.2
  mobile_scanner: ^5.2.3
  http: ^1.3.0
  uuid: ^4.5.1
  shared_preferences: ^2.3.5
  intl: ^0.20.2
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
